//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaPublicWebsite.BusinessLogic.Resources.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EpcHeatingType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EpcHeatingType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeaPublicWebsite.BusinessLogic.Resources.Enum.EpcHeatingType", typeof(EpcHeatingType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biomass boiler.
        /// </summary>
        public static string Biomass {
            get {
                return ResourceManager.GetString("Biomass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal or solid fuel heating.
        /// </summary>
        public static string CoalOrSolidFuel {
            get {
                return ResourceManager.GetString("CoalOrSolidFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct acting electric heating.
        /// </summary>
        public static string DirectActionElectric {
            get {
                return ResourceManager.GetString("DirectActionElectric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know.
        /// </summary>
        public static string DoNotKnow {
            get {
                return ResourceManager.GetString("DoNotKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas boiler.
        /// </summary>
        public static string GasBoiler {
            get {
                return ResourceManager.GetString("GasBoiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat pump.
        /// </summary>
        public static string HeatPump {
            get {
                return ResourceManager.GetString("HeatPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG boiler.
        /// </summary>
        public static string LpgBoiler {
            get {
                return ResourceManager.GetString("LpgBoiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil boiler.
        /// </summary>
        public static string OilBoiler {
            get {
                return ResourceManager.GetString("OilBoiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage heaters.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
    }
}
