version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    # we may not be able to respond to pull requests immediately
    # prioritise showing them all
    open-pull-requests-limit: 100
    # group together minor & patch updates. major ones get a PR per change
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "SeaPublicWebsite"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    # group all npm updates
    groups:
      npm:
        update-types:
          - "major"
          - "minor"
          - "patch"
