version: '3.8'

services:
  sea:
    build: .
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: seadev
    ports:
      - "5432:5432"