name: "Website Error or Fatal log"
type: any
index: "*-*"

filter:
- term:
     environmentName: "Production"
- terms:
     level: ["Error", "Fatal"]
 
alert:
- "email"

email:
- "homeenergyretrofitadvice@beis.gov.uk"
- "dan.corder@softwire.com"