//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaPublicWebsite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeaPublicWebsite.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your address.
        /// </summary>
        internal static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a building number or name.
        /// </summary>
        internal static string BuildingNumberOrNameRequired {
            get {
                return ResourceManager.GetString("BuildingNumberOrNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select bungalow type.
        /// </summary>
        internal static string BungalowTypeRequired {
            get {
                return ResourceManager.GetString("BungalowTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if your cavity walls are insulated.
        /// </summary>
        internal static string CavityWallInsulationRequired {
            get {
                return ResourceManager.GetString("CavityWallInsulationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm whether or not this certificate belongs to your address before continuing.
        /// </summary>
        internal static string CertificateBelongsToAddressRequired {
            get {
                return ResourceManager.GetString("CertificateBelongsToAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address.
        /// </summary>
        internal static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select flat type.
        /// </summary>
        internal static string FlatTypeRequired {
            get {
                return ResourceManager.GetString("FlatTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how your floor is built.
        /// </summary>
        internal static string FloorConstructionTypeRequired {
            get {
                return ResourceManager.GetString("FloorConstructionTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if the floor is insulated.
        /// </summary>
        internal static string FloorInsulatedRequired {
            get {
                return ResourceManager.GetString("FloorInsulatedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select glazing type.
        /// </summary>
        internal static string GlazingTypeRequired {
            get {
                return ResourceManager.GetString("GlazingTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether you have a hot water cylinder.
        /// </summary>
        internal static string HasHotWaterCylinderRequired {
            get {
                return ResourceManager.GetString("HasHotWaterCylinderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether you have outdoor space.
        /// </summary>
        internal static string HasOutdoorSpaceRequired {
            get {
                return ResourceManager.GetString("HasOutdoorSpaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number of hours in the afternoon and evening.
        /// </summary>
        internal static string HeatingInAfternoonAndEveningHoursRequired {
            get {
                return ResourceManager.GetString("HeatingInAfternoonAndEveningHoursRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number of hours in the morning.
        /// </summary>
        internal static string HeatingInMorningHoursRequired {
            get {
                return ResourceManager.GetString("HeatingInMorningHoursRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your main heating system.
        /// </summary>
        internal static string HeatingSystemRequired {
            get {
                return ResourceManager.GetString("HeatingSystemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select house type.
        /// </summary>
        internal static string HouseTypeRequired {
            get {
                return ResourceManager.GetString("HouseTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if you have loft access.
        /// </summary>
        internal static string LoftAccessRequired {
            get {
                return ResourceManager.GetString("LoftAccessRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if you have a loft space.
        /// </summary>
        internal static string LoftSpaceRequired {
            get {
                return ResourceManager.GetString("LoftSpaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of hours must be between {1} and {2}.
        /// </summary>
        internal static string NumberOfHoursIntRange {
            get {
                return ResourceManager.GetString("NumberOfHoursIntRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of people who live in the property must be between {1} and {2}..
        /// </summary>
        internal static string NumberOfOccupantsIntRange {
            get {
                return ResourceManager.GetString("NumberOfOccupantsIntRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your main heating system.
        /// </summary>
        internal static string OtherHeatingTypeRequired {
            get {
                return ResourceManager.GetString("OtherHeatingTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your circumstances.
        /// </summary>
        internal static string OwnershipStatusRequired {
            get {
                return ResourceManager.GetString("OwnershipStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a postcode.
        /// </summary>
        internal static string PostcodeRequired {
            get {
                return ResourceManager.GetString("PostcodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select property type.
        /// </summary>
        internal static string PropertyTypeRequired {
            get {
                return ResourceManager.GetString("PropertyTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what to do with this recommendation.
        /// </summary>
        internal static string RecommendationActionRequired {
            get {
                return ResourceManager.GetString("RecommendationActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your 8-character reference code (or choose the &apos;This is my first visit&apos; option).
        /// </summary>
        internal static string ReferenceRequired {
            get {
                return ResourceManager.GetString("ReferenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select roof type.
        /// </summary>
        internal static string RoofConstructionRequired {
            get {
                return ResourceManager.GetString("RoofConstructionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if the roof is insulated.
        /// </summary>
        internal static string RoofInsulatedRequired {
            get {
                return ResourceManager.GetString("RoofInsulatedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm whether or not you would like to search for your EPC before continuing.
        /// </summary>
        internal static string SearchForEPCConfirmationRequired {
            get {
                return ResourceManager.GetString("SearchForEPCConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which country the property is located in.
        /// </summary>
        internal static string SelectPropertyCountryRequired {
            get {
                return ResourceManager.GetString("SelectPropertyCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if your solid walls are insulated.
        /// </summary>
        internal static string SolidWallsInsulatedRequired {
            get {
                return ResourceManager.GetString("SolidWallsInsulatedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temperature must be between {1} and {2}..
        /// </summary>
        internal static string TemperatureDecimalRange {
            get {
                return ResourceManager.GetString("TemperatureDecimalRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English used service before.
        /// </summary>
        internal static string UsedServiceBeforeRequired {
            get {
                return ResourceManager.GetString("UsedServiceBeforeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select wall type.
        /// </summary>
        internal static string WallConstructionRequired {
            get {
                return ResourceManager.GetString("WallConstructionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what year your property was built.
        /// </summary>
        internal static string YearBuiltRequired {
            get {
                return ResourceManager.GetString("YearBuiltRequired", resourceCulture);
            }
        }
    }
}
