namespace SeaPublicWebsite.BusinessLogic.Models.Enums;

public enum QuestionFlowStep
{
    Start, //TODO Localise further
    NewOrReturningUser,
    Country,
    OwnershipStatus,
    ServiceUnsuitable,
    FindEpc,
    AskForPostcode,
    ConfirmAddress,
    ConfirmEpcDetails,
    NoEpcFound,
    PropertyType,
    HouseType,
    BungalowType,
    FlatType,
    HomeAge,
    CheckYourUnchangeableAnswers,
    WallConstruction,
    CavityWallsInsulated,
    SolidWallsInsulated,
    FloorConstruction,
    FloorInsulated,
    RoofConstruction,
    LoftSpace,
    LoftAccess,
    RoofInsulated,
    GlazingType,
    OutdoorSpace,
    HeatingType,
    OtherHeatingType,
    HotWaterCylinder,
    NumberOfOccupants,
    HeatingPattern,
    Temperature,
    AnswerSummary,
    NoRecommendations,
    YourRecommendations
}