//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaPublicWebsite.Resources.Bre {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecommendationServiceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecommendationServiceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeaPublicWebsite.Resources.Bre.RecommendationServiceText", typeof(RecommendationServiceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the level of insulation in your loft to the recommended level of 300mm.
        /// </summary>
        public static string SummaryAddLoftInsulation {
            get {
                return ResourceManager.GetString("SummaryAddLoftInsulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulate the ground floor.
        /// </summary>
        public static string SummaryFloorInsulationSuspendedFloor {
            get {
                return ResourceManager.GetString("SummaryFloorInsulationSuspendedFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to high heat retention storage heaters.
        /// </summary>
        public static string SummaryHighHeatRetentionStorageHeaters {
            get {
                return ResourceManager.GetString("SummaryHighHeatRetentionStorageHeaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulate your hot water cylinder.
        /// </summary>
        public static string SummaryHotWaterCylinderInsulation {
            get {
                return ResourceManager.GetString("SummaryHotWaterCylinderInsulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat pumps use the energy outside to heat your home and hot water.
        /// </summary>
        public static string SummaryInstallHeatPump {
            get {
                return ResourceManager.GetString("SummaryInstallHeatPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject insulation into the cavity in your external walls.
        /// </summary>
        public static string SummaryInsulateCavityWalls {
            get {
                return ResourceManager.GetString("SummaryInsulateCavityWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulate your solid walls (brick walls age A-D).
        /// </summary>
        public static string SummaryInsulateSolidWalls {
            get {
                return ResourceManager.GetString("SummaryInsulateSolidWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulate your solid walls (other wall types).
        /// </summary>
        public static string SummaryInsulateSolidWallsOther {
            get {
                return ResourceManager.GetString("SummaryInsulateSolidWallsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add loft insulation to reach the recommended level of 300mm.
        /// </summary>
        public static string SummaryInsulateYourLoft {
            get {
                return ResourceManager.GetString("SummaryInsulateYourLoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace old single glazed windows with new double or triple glazing.
        /// </summary>
        public static string SummaryReplaceSingleGlazedWindowsWithDoubleOrTripleGlazing {
            get {
                return ResourceManager.GetString("SummaryReplaceSingleGlazedWindowsWithDoubleOrTripleGlazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install PV panels on your roof to generate electricity.
        /// </summary>
        public static string SummarySolarElectricPanels {
            get {
                return ResourceManager.GetString("SummarySolarElectricPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit a programmer, thermostat and thermostatic radiator valves.
        /// </summary>
        public static string SummaryUpgradeHeatingControls {
            get {
                return ResourceManager.GetString("SummaryUpgradeHeatingControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add some more loft insulation.
        /// </summary>
        public static string TitleAddLoftInsulation {
            get {
                return ResourceManager.GetString("TitleAddLoftInsulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulate the ground floor.
        /// </summary>
        public static string TitleFloorInsulationSuspendedFloor {
            get {
                return ResourceManager.GetString("TitleFloorInsulationSuspendedFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to high heat retention storage heaters.
        /// </summary>
        public static string TitleHighHeatRetentionStorageHeaters {
            get {
                return ResourceManager.GetString("TitleHighHeatRetentionStorageHeaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulate your hot water cylinder.
        /// </summary>
        public static string TitleHotWaterCylinderInsulation {
            get {
                return ResourceManager.GetString("TitleHotWaterCylinderInsulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a heat pump.
        /// </summary>
        public static string TitleInstallHeatPump {
            get {
                return ResourceManager.GetString("TitleInstallHeatPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulate your cavity walls.
        /// </summary>
        public static string TitleInsulateCavityWalls {
            get {
                return ResourceManager.GetString("TitleInsulateCavityWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulate your solid walls.
        /// </summary>
        public static string TitleInsulateSolidWalls {
            get {
                return ResourceManager.GetString("TitleInsulateSolidWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulate your solid walls.
        /// </summary>
        public static string TitleInsulateSolidWallsOther {
            get {
                return ResourceManager.GetString("TitleInsulateSolidWallsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulate your loft.
        /// </summary>
        public static string TitleInsulateYourLoft {
            get {
                return ResourceManager.GetString("TitleInsulateYourLoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit new windows.
        /// </summary>
        public static string TitleReplaceSingleGlazedWindowsWithDoubleOrTripleGlazing {
            get {
                return ResourceManager.GetString("TitleReplaceSingleGlazedWindowsWithDoubleOrTripleGlazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit solar electric panels.
        /// </summary>
        public static string TitleSolarElectricPanels {
            get {
                return ResourceManager.GetString("TitleSolarElectricPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade your heating controls.
        /// </summary>
        public static string TitleUpgradeHeatingControls {
            get {
                return ResourceManager.GetString("TitleUpgradeHeatingControls", resourceCulture);
            }
        }
    }
}
