name: Delete old data

on:
  schedule:
    - cron:  '*/10 * * * *'

  workflow_dispatch:

jobs:
  call-build-and-deploy-workflow:
    uses: ./.github/workflows/_build-and-deploy-to-gov-paas.yml
    with:
      environment_name: loadtest
    secrets:
      gov_paas_password: ${{ secrets.TEAM_BEISESASSUPPORT_GOV_PAAS_PASSWORD }}

  delete-data:
    runs-on: ubuntu-latest
    steps:
    - name: Delete old data
      run: cf run-task sea-beta-loadtest --command "echo 1" --name delete-old-data-task

